### ISSUE TITLE
Commands do not work

### ISSUE THREAD

**Issue by uwoneko** [Wyliemaster/GDPS-Bot#4]
**Command do not work, here is console errors:**

**Level command:**

[LOG] ERROR: song does not exist - Server Response: undefined
/app/commands/level.js:156
songTrim = body.split('#')[2] //Credits to Colon and a few members from GDP for explaining what i need to do for this
                ^

TypeError: Cannot read property 'split' of undefined
    at Request.callback [as _callback] (/app/commands/level.js:156:17)
    at self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Profile command:**

/app/commands/profile.js:119
} else if(data['youTube'].length < 15){
                          ^

TypeError: Cannot read property 'length' of undefined
    at Request.callback [as _callback] (/app/commands/profile.js:119:27)
    at self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Leaderboard command:**

/app/commands/leaderboard.js:93
split = body.split('|')
             ^

TypeError: Cannot read property 'split' of undefined
    at Request.callback [as _callback] (/app/commands/leaderboard.js:93:14)
    at self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21

**Comment by uwoneko** [comment]
Sorry, just a typo.
